version: 2.0
jobs:
  build_website:
    docker:
      - image: circleci/ruby:2.3-browsers
    working_directory: ~/website
    steps:
      - checkout
      - run: 
          name: Build Website
          command: make            
      - persist_to_workspace:
          root: ~/website
          paths:
            - build/*

  deploy_website:
    docker:
      - image: circleci/python:2.7-browsers
    working_directory: ~/website
    steps:
      - attach_workspace:
          at: ~/website
      - run:
          name: Release Website
          command: |
            sudo apt-get update && sudo apt-get install -y awscli
            aws s3 sync ./build/ s3://www.connormckelvey.com/ --acl public-read

workflows:
  version: 2
  build_and_release:
    jobs:
      - build_website
      - deploy_website:
          requires:
            - build_website
          filters:
            branches:
              only: master